version: '3.7'
services:
  app_frontend:
    container_name: app_frontend
    environment:
      - HTTP_URL=http://ec2-3-86-166-95.compute-1.amazonaws.com:4001
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8082:8080'
