version: '3.7'

services:

  app_frontend:
    container_name: app_frontend
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true