version: '3.7'
services:
  app_frontend:
    container_name: app_frontend
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
